<?php

use Illuminate\Database\Seeder;

class CardsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cards')->delete();
        
        \DB::table('cards')->insert(array (
            0 => 
            array (
                'id' => 1,
                'service_id' => 1,
                'category_id' => 2,
                'name' => 'Black Business Cards',
                'description' => 'Our black business cards are created exactly the same as our duplex black card stock. Formed by gluing together two pieces of approximately 280 gsm paper, this uncoated paper stock is a favorite for foil stamping. A variety of foil colours look excellent on this stock, and create a business card with a refined appearance. Please note if a design is close or goes to the edge of the card there is an additional fee for 30% of the total price.',
                'turnaround_time' => '12 - 16 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'visiting card, embossing,  black card, black business cards, creative business cards, foil stamping, gold foil, emboss, thermography, debossing, die cutting, laser engraving.',
                'meta_description' => 'Rockdesign\'s black business cards comes with premium black uncoated card stock that\'s high quality and thick. We offer various unique printing features such as foil stamping, gold foil, emboss, thermography, deboss, die cutting and much more. Rockdesign provide free business card templates for all our customers. Get your black business cards online today at Rockdesign.com',
                'weight' => 0.01000000000000000020816681711721685132943093776702880859375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'black-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-07 00:28:12',
                'updated_at' => '2016-02-12 15:29:45',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'service_id' => 1,
                'category_id' => 2,
                'name' => 'Duplex Business Cards',
                'description' => 'Our duplex business cards are one of our best selling card stocks and are amongst a favourite of RockDesignâ€™s customers. With a thickness of 25.6pt, this card is thick enough to be high end yet fits perfectly into a wallet. The popular â€œAutomaticaâ€ layout is available template for this card stock. If you wish to have a customized duplex card stock please contact RockDesign for a custom quote. Please note if a design is close or goes to the edge of the card there is an additional fee for 30% of the total price.',
                'turnaround_time' => '12 - 16 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'creative business cards, foil stamping, gold foil, emboss, thermography, duplex business cards, premium business cards',
                'meta_description' => 'Rockdesign\'s black and white duplex business cards comes with premium black uncoated card stock that\'s high quality and thick. We offer various unique printing features such as foil stamping, gold foil, emboss, thermography, deboss, die cutting and much more. Rockdesign provide free business card templates for all our customers. Get your black business cards online today at Rockdesign.com',
                'weight' => 0.01000000000000000020816681711721685132943093776702880859375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'duplex-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-07 02:59:19',
                'updated_at' => '2016-02-09 22:19:06',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'service_id' => 1,
                'category_id' => 1,
                'name' => 'Triplex Business Cards',
                'description' => 'If you are looking for a card that is incredibly thick and high end this is the card for you. This three layered card stock comes in three immediate stocks; black/white/black, black/orange/black, and black/red/black. If you would like a specific colour combination please contact us for a custom quote. Perfect for debossing and foil stamping, these are cards that are sure to impress. Designs that go close to the edge of the card or extend to the edge of the card require a 30% additional charge.',
                'turnaround_time' => '12 - 16 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'luxury business cards, triplex business cards, high end business cards, best business cards, visiting card design, foil stamping, embossing, deboss, die cutting',
                'meta_description' => 'Rockdesign\'s triplex business cards comes with various color of premium card stocks.  We offer various unique printing features such as foil stamping, gold foil, emboss, thermography, deboss, die cutting and much more. Rockdesign provide free business card templates for all our customers. Get your black business cards online today at Rockdesign.com',
                'weight' => 0.01000000000000000020816681711721685132943093776702880859375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'triplex-business-cards',
                'pricing' => 1,
                'atleast_one' => 0,
                'status' => 1,
                'created_at' => '2016-02-07 03:23:41',
                'updated_at' => '2016-03-30 19:55:31',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'service_id' => 1,
                'category_id' => 2,
                'name' => 'Smooth Uncoated Business Cards',
            'description' => 'Our smooth white and cream uncoated card stocks are one of our most popular due to the variety of weights it comes in. Whether you want your cards to be slim or sturdy, the smooth white uncoated paper stock will fit your preferred density. The 29.5pt also qualifies for edge painting and works very well for debossing. Please note a full bleed deboss (for example the back side of the Midnight Studio card) requires a 30% charge of the total cost.',
                'turnaround_time' => '12 - 16 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'letterpress, creative business cards, foil stamping, gold foil, emboss, thermography, debossing, premium business cards, name card, visiting card',
                'meta_description' => 'Order your own set of Smooth Uncoated cards online today. Available in various card thickness and print features, such as embossing, deboss, letterpress, offset printing, foil stamping and much more ! 
',
                'weight' => 0.01000000000000000020816681711721685132943093776702880859375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'smooth-uncoated-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-07 13:24:50',
                'updated_at' => '2016-03-20 22:31:15',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'service_id' => 1,
                'category_id' => 2,
                'name' => 'Premium Uncoated Business Cards',
                'description' => 'The premium white uncoated card stock is a well rounded card stock because of the variety of printing features that it is able to have. This bright white paper contains small flecks of fibers throughout which give a sophisticated yet natural charm to business cards printed with this paper stock. The card stock is measures in 17.4pt which is not too thick yet not too thin. It is ideal for embossing, offset printing, and foil stamping. Offset printing is considered a finish, so calculate costs accordingly!',
                'turnaround_time' => '12 - 16 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'premium business cards, gold foil, embossing, business card design, visiting card design',
                'meta_description' => 'Order Premium Uncoated Business cards online. Select your desired quantity, print features, and upload your own design file',
                'weight' => 0.01000000000000000020816681711721685132943093776702880859375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'premium-uncoated-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-07 13:39:46',
                'updated_at' => '2016-03-20 22:29:28',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'service_id' => 1,
                'category_id' => 1,
                'name' => 'Hard Suede Business Cards',
            'description' => 'The hard suede card stock is sure to be one of our most beautiful card stocks we have to offer here at RockDesign. The card is a duplex card stock so you may wish to choose from the following three duplex paper stocks available; black/black, black/white, and white/white. If you are looking for a thick and sturdy card stock that is soft to the touch this is the perfect card stock for you. Foil stamping is ideal for the black hard suede but we do offer offset printing on the white hard suede paper stock. Please do note while you are finding a quote that we charge 30% extra for designs that are close to the edge or extend to the edge of the card (full bleed). Edge foil painting is available for this card stock as well. Order yours today!',
                'turnaround_time' => '12 - 16 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'Suede business Cards, Unique business cards, black business cards, foil stamping, edge painting business cards, luxury name card',
                'meta_description' => 'Order Rockdesign\'s Hard Suede Business Cards today ! Available in various card thickness and print features, such as deboss, offset printing, foil stamping and much more ! ',
                'weight' => 0.01000000000000000020816681711721685132943093776702880859375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'hard-suede-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-07 14:00:22',
                'updated_at' => '2016-03-20 23:05:36',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'service_id' => 1,
                'category_id' => 1,
                'name' => 'Soft Suede Business Cards',
                'description' => 'The name of the card explains it all. The soft suede card is smooth, sleek, and sublime while matching the look and feel of suede. The card stock weighs in at 25pt so it is most fitting for foil stamping or embossing. We have a new type of embossing called, â€œ3D embossingâ€ that works great for soft suede cards. Please note if you have a design that goes close to the edge of the card or extends right to the edge of the card there is a 30% additional charge.',
                'turnaround_time' => '12 - 16 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'Luxury business cards, suede business cards, embossing, foil stamping, die cutting, offset printing',
                'meta_description' => 'Order our Luxury Soft Suede Business Cards today at RockDesign.com. Available in various card thickness and print features, such as embossing, deboss, offset printing, foil stamping and much more ! ',
                'weight' => 0.01299999999999999940325512426397835952229797840118408203125,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'soft-suede-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-07 14:21:35',
                'updated_at' => '2016-03-20 23:04:02',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'service_id' => 1,
                'category_id' => 2,
                'name' => 'Letterpress Business Cards',
            'description' => 'Letterpress printing originated in the 1400s and was the primary system of printing for more than 500 years. Today, letterpress is a great addition to text on a business card by incorporating a relief into the paper. Thus type is imprinted on the card stock and creates itâ€™s own special design element. Letterpress coincides perfectly with a debossed logo or foil stamping. Letterpress is recommended for card stocks that are 29.5pt or higher in thickness. For this card we have set the default card stock as our 30pt classic white uncoated card stock (also available in cream).',
                'turnaround_time' => '12 - 16 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.
',
                'guide_link' => '',
                'meta_tag' => 'letterpress business cards, creative business cards, letterpress, deboss, embossing, thick name card',
                'meta_description' => 'Design and print customized Letterpress Business Cards with RockDesign. Available in various card thickness and print features, such as embossing, deboss, letterpress, offset printing, foil stamping and much more ! ',
                'weight' => 0.01600000000000000033306690738754696212708950042724609375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'letterpress-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-08 02:38:23',
                'updated_at' => '2016-03-20 22:27:01',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'service_id' => 1,
                'category_id' => 2,
                'name' => 'Brown Kraft Business Cards',
                'description' => 'Our Brown Kraft Business Cards are created exactly the same as our duplex black card stock. Formed by gluing together two pieces of approximately 280 gsm paper, this uncoated paper stock is a favourite for foil stamping. A variety of foil colours look excellent on this stock, and create a business card with a refined appearance. Please note if a design is close or goes to the edge of the card there is an additional fee for 30% of the total price.',
                'turnaround_time' => '12 - 16 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.
',
                'guide_link' => '',
                'meta_tag' => 'creative business cards, Kraft visit card, Brown name card, Cool business Cards, Vintage Business Cards',
                'meta_description' => 'Order or creative Brown Kraft Business Cards Today. Select your preferred print finishing : such as embossing, deboss, letterpress, offset printing, foil stamping and much more ! ',
                'weight' => 0.0120000000000000002498001805406602215953171253204345703125,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'brown-kraft-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-08 19:03:18',
                'updated_at' => '2016-03-20 22:24:41',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'service_id' => 1,
                'category_id' => 2,
                'name' => '32PT Silk Business Cards',
                'description' => 'Our ultra thick silk card stock brings a luxurious edge to silk business cards. They are an excellent option for printing images and a variety of colors! Recommended finishings include spot uv, offset printing, and foil stamping. With a well designed business card, this card stock creates a statement and suits almost all designs.',
                'turnaround_time' => '12 - 16 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'Thick business cards, spot uv, gold foil, silk laminated business cards, offset printing, name card',
                'meta_description' => 'Order 32pt Silk Business Cards from our Premium collection. Select your preferred print finishing, size, and quantity when you place your online order',
                'weight' => 0.01600000000000000033306690738754696212708950042724609375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => '32pt-silk-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-08 19:14:54',
                'updated_at' => '2016-03-18 14:15:17',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'service_id' => 1,
                'category_id' => 2,
                'name' => 'Gray Business Cards',
                'description' => 'The gray business card is an excellent alternative for those who are looking for an uniquely coloured card stock. Similar to the duplex business card, this card stock is also composed of two sheets of paper stock adhered together for a total thickness of 24.6pt. This minimal, exquisite card stock is perfect for those who want something contemporary and cutting edge. Please note if a design is close or goes to the edge of the card there is an additional fee for 30% of the total price.',
                'turnaround_time' => '12 - 16 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.
',
                'guide_link' => '',
                'meta_tag' => 'Grey business cards, creative business cards, online printing, name card, visiting card design',
                'meta_description' => 'Order Light or Dark Gray Business Cards. Choose your preferred print finishing such as foil stamping, embossing, deboss, edge foil, offset printing and much more ! ',
                'weight' => 0.0109999999999999993616217608405349892564117908477783203125,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'gray-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-08 19:30:01',
                'updated_at' => '2016-03-18 14:13:03',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'service_id' => 1,
                'category_id' => 5,
                'name' => 'Black Metal Business Cards',
                'description' => 'Our black metal cards radiate an industrial exquisiteness that makes them leave a lasting impression. The pricing for these cards include etching, cut through, and a die cut. With an amazing design each card become a truly unique and unforgettable piece.',
                'turnaround_time' => '14- 20 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'Black Metal Business Card, Metal Business Cards, Black Card, Unique business cards, etching, laser engraving',
                'meta_description' => 'Our black metal cards are an exquisite addition to any business. Crafted from 0.5mm black anodized stainless steel these cards are as powerful as a solid hand shake. The base price of these cards includes non-bleed etching, as well as custom die cut and cut through with in our standard business card size of 3.5â€x2â€. Laser engraving can be used on these cards to create a metallic appearance to a design and spot colour can be used to add solid colours to accentuate your companyâ€™s branding. Variable data',
                'weight' => 0.040000000000000000832667268468867405317723751068115234375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'black-metal-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-09 14:19:27',
                'updated_at' => '2016-03-20 23:00:41',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'service_id' => 1,
                'category_id' => 5,
                'name' => 'Stainless Steel Business Cards',
            'description' => 'We offer three types of finishings for our stainless steel cards; brush, mirror, and original. These cards are perfect for the individual or business who want to stand out amongst others. Etch, engrave, or cut through almost any text, logo, or pattern. Ink printing, variable data (ex: number ranges), and engraving all require additional costs.',
                'turnaround_time' => '14- 20 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.
',
                'guide_link' => '',
                'meta_tag' => 'Stainless Steel Business Cards, Stainless Steel name card, Metal Business cards, Unique visiting cards, Etching, Cut Through, Laser Engraving',
                'meta_description' => 'Order Stainless Steel Business cards online at RockDesign.com. Available with various thickness and print finishing such as etching, laser engraving, cut through, UV printing.',
                'weight' => 0.040000000000000000832667268468867405317723751068115234375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'stainless-steel-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-09 14:47:24',
                'updated_at' => '2016-03-20 22:58:51',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'service_id' => 1,
                'category_id' => 5,
                'name' => 'Gold Metal Business Cards',
                'description' => 'The brass metal cards are our latest metal card to offer. Very much alike to the black metal and stainless steel cards, the price below includes etching, cut through, and a die cut. Give your clients the gift of gold by handing out a card that will resemble just that!',
                'turnaround_time' => '14 - 20 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.
',
                'guide_link' => '',
                'meta_tag' => 'Gold Business Card, Gold Metal Business Cards, Metal Name Card, Luxury business cards, etching, laser engraved',
                'meta_description' => 'Order our Gold Metal Business Cards today at RockDesign.com. This luxurious gold metal visiting cards comes with print features such as: Etching, Laser Engraving, UV printing, Cut through and much more ! ',
                'weight' => 0.040000000000000000832667268468867405317723751068115234375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'gold-metal-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-09 14:55:40',
                'updated_at' => '2016-03-20 22:56:35',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'service_id' => 1,
                'category_id' => 6,
                'name' => 'Frost Business Cards',
                'description' => 'Our frost business cards are an affordable 1 sided UV printing card. The frost finishing has a textured appeal that sets them aside from traditional plastic cards.',
                'turnaround_time' => '10 - 12 Business Days + Transit Time* Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'Plastic business cards, transparent visiting cards, cool name card, UV printing, cheap business cards',
                'meta_description' => 'Get your plastic frost business cards today at RockDesign.com. This unique name card has  special frost texture on the surface and it comes with 1 sided UV printing.',
                'weight' => 0.01000000000000000020816681711721685132943093776702880859375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'frost-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-09 17:38:41',
                'updated_at' => '2016-03-20 22:53:20',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'service_id' => 1,
                'category_id' => 6,
                'name' => 'Frost PVC Business Cards',
            'description' => 'The Frost PVC plastic card is ideal for 1 sided UV printing. We are able to print white ink at an additional cost. Foil stamping is also available on this type of plastic card stock at an additional price. The card stock is a smooth transparent plastic and comes in the size of a standard credit card size (approximately 3.35 x 2 inches).',
                'turnaround_time' => '10 - 12 Business Days + Transit Time* Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'Plastic Business Cards, Frost Name Card, Transparent visiting card, unique name card design',
                'meta_description' => 'Customize your order of Frost PVC Business cards online. Available with features such as: Silver Foil, Gold Foil, UV Printing. Select your desired quantity, print features, and upload your own design file ',
                'weight' => 0.01000000000000000020816681711721685132943093776702880859375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'frost-pvc-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-09 17:41:54',
                'updated_at' => '2016-03-20 22:49:49',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'service_id' => 1,
                'category_id' => 6,
                'name' => 'Clear Business Cards',
                'description' => 'Our 14pt clear plastic cards are a beautiful and unique option. These cards are ideal for full bleed printing, white ink and can be foil stamped in gold, silver or black. Only one sided design can be printed on this cardstock due to their transparent nature. ',
                'turnaround_time' => '10 - 12 Business Days + Transit Time
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'plastic business cards, unique business cards, visiting card design, clear business card, transparent name card',
                'meta_description' => 'Customize your order of Clear Plastic Business cards online. Choose your print features such as: Gold Foil Stamping, Silver Foil Stamping, UV Printing. ',
                'weight' => 0.01000000000000000020816681711721685132943093776702880859375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'clear-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-09 17:44:38',
                'updated_at' => '2016-03-20 22:47:33',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'service_id' => 1,
                'category_id' => 7,
                'name' => '2 sided Spot UV Business Cards',
                'description' => 'The 16pt gloss stock is a popular choice for people looking for an affordable option and high end print features. The pricing includes a smooth silk lamination over top the card stock, 2 sided offset printing and 2 sided Spot UV. Foil stamping is also available for this card stock for an additional fee. Spot UV looks great on logos, larger text, and can also be used to create a transparent pattern over top of the card.
',
                'turnaround_time' => '7 - 10 business days + transit time* Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.
',
                'guide_link' => '',
                'meta_tag' => 'spot UV business cards, Spot UV, Offset Printing, Cheap business cards, Rounded corners business cards',
                'meta_description' => 'Order 2 Sided Spot UV Classic Business cards online. Select your desired print finishings such as : offset printing, embossing, spot UV, rounded corner die cutting, foil stamping and more !',
                'weight' => 0.0040000000000000000832667268468867405317723751068115234375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => '2-sided-spot-uv-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-09 17:46:41',
                'updated_at' => '2016-03-20 22:43:20',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'service_id' => 1,
                'category_id' => 7,
                'name' => 'Natural Cream Uncoated Business Cards',
                'description' => 'The natural cream card stock is perfect for those looking for a subtle hint of colour to their cards. This card stock is more of an off-white, natural looking stock, fitting for offset printing and foil stamping.',
                'turnaround_time' => '7 - 10 business days + transit time* Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'cheap business cards, print name card online, offset printing, foil stamping',
                'meta_description' => 'Order Natural Cream Uncoated Business cards online. Available with print features such as : Embossing, Foil Stamping, Offset Printing and more.',
                'weight' => 0.0040000000000000000832667268468867405317723751068115234375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'natural-cream-uncoated-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-09 17:47:22',
                'updated_at' => '2016-03-20 22:41:20',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'service_id' => 1,
                'category_id' => 7,
                'name' => 'Regular Suede Business Cards',
                'description' => 'One of our newest card stocks available at RockDesign. The regular suede card is an impeccable fusion between a Style and High End card. This card stock is velvet smooth to the touch yet is flexible and resilient to tearing. For optimal use of this card stock we recommend offset printing, spot UV, and foil stamping.',
                'turnaround_time' => '7 - 10 business days + transit time* Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'Suede Business cards, Spot UV business cards, foil stamping, cheap business cards, cheap name card, offset printing, Spot UV',
                'meta_description' => 'Order Regular Suede Business Cards online. Select your desired quantity and print finishings such as : Spot UV, Offset printing, Foil Stamping, Embossing and more !',
                'weight' => 0.0040000000000000000832667268468867405317723751068115234375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'regular-suede-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-09 17:47:58',
                'updated_at' => '2016-03-20 22:38:57',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'service_id' => 1,
                'category_id' => 8,
                'name' => 'Laser Engraved Black Business Cards',
                'description' => 'Our laser engraved black business cards are an ideal high end option for clients on a tight deadline. Laser engraving creates a beautiful beige look that is carved into the 28pt uncoated black cardstock. The turnaround time for this is 3-5 business days after proof approval plus transit however for a surcharge we may be able to reduce this time to 48 hours as a rush service. All rush services are assessed on a case by case basis. These cards are perfect for clients in a hurry who do not want to compromise on card quality.
',
                'turnaround_time' => '3 - 5 Business Days + Transit Time* 
For rush order, please contact our sales department
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.
',
                'guide_link' => '',
                'meta_tag' => 'quick business cards, quick print, laser cards, fast name card, laser engraving, laser cutting',
            'meta_description' => 'Order Laser Engraved Black Metal Business Cards today! Choose from small order quantities with quick (3 to 5 business day) turnaround time',
                'weight' => 0.007000000000000000145716771982051795930601656436920166015625,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'laser-engraved-black-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-09 17:53:03',
                'updated_at' => '2016-03-18 14:07:57',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'service_id' => 1,
                'category_id' => 8,
                'name' => 'Laser Engraved Black Metal Business Cards',
                'description' => 'In need of some business cards immediately but donâ€™t want to order a large quantity? At RockDesign we are now offering laser engraved black stainless steel cards for those who are in a rush to have their cards in their hands. We will have existing templates that include cut through so your cards can still have that special touch. Rush orders will take 48 hours to produce while we recommend 3-5 business days for our standard production time. Please take into consideration before choosing our laser engraved cards that laser engraving is not ideal for extremely small type or small intricate designs.',
                'turnaround_time' => '3 - 5 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.
',
                'guide_link' => '',
                'meta_tag' => 'quick business cards, laser engraving, metal business cards, black metal cards, creative business cards.',
            'meta_description' => 'Order Laser Engraved Black Business Cards today! Choose from small order quantities with quick (3 to 5 business day) turnaround time.',
                'weight' => 0.040000000000000000832667268468867405317723751068115234375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'laser-engraved-black-metal-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-09 17:54:16',
                'updated_at' => '2016-03-18 14:10:48',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'service_id' => 1,
                'category_id' => 5,
                'name' => 'Luxury Black Metal Business Cards',
                'description' => 'Our Black luxury Metal Cards are with out a doubt a show stopper. On our ultra thick 0.5mm thick black anodized stainless steel metal these cards are the perfect way to depict your success. Available in both frost and prism finish these finger print resistant cards make perfect VIP membership cards and can be combined with etching and spot colour. Custom die cut, non-bleed etching and frost or prism finish are all specifications that are included in the base price of this card.',
                'turnaround_time' => '14- 20 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'Luxury business cards, metal business cards, laser engraving, etching, visiting card design, creative business cards, visit card, ',
                'meta_description' => 'Order your Luxury Black Metal Business Cards today at Rockdesign.com. Available in both frost and prism finish these finger print resistant cards make perfect VIP membership cards and can be combined with etching and spot colour. ',
                'weight' => 0.040000000000000000832667268468867405317723751068115234375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'luxury-black-metal-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-02-17 13:02:22',
                'updated_at' => '2016-03-20 22:34:43',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 25,
                'service_id' => 1,
                'category_id' => 11,
                'name' => 'Laser Engraved Acrylic Business Cards',
            'description' => 'The newest addition to the RockDesign roaster is these beautiful, crystal clear acrylic cards. These one sided transparent cards are produced using laser engraving on our ultra thick 3mm acrylic cardstock. Available in 5 colour options (clear, black, blue, florescent green and florescent orange) this cardstock is perfect for clients looking to buy unique and modern cards in small quantities.',
                'turnaround_time' => '3 - 5 Business Days + Transit Time* 
For rush order, please contact our sales department
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.
',
                'guide_link' => '',
                'meta_tag' => 'creative business cards, clear business cards, acrylic business cards, cool business cards, visiting card design, best business cards',
                'meta_description' => 'The one of the most unique business cards in the market, Rockdesign\'s Laser Engraved Acrylic Business Cards. Available in various colours, and it comes with features such as laser engraving, laser cut and more.',
                'weight' => 0.040000000000000000832667268468867405317723751068115234375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'laser-engraved-acrylic-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-03-07 04:41:15',
                'updated_at' => '2016-03-18 13:58:19',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 30,
                'service_id' => 1,
                'category_id' => 5,
                'name' => 'Rose Gold Metal Business Cards',
                'description' => 'Our elegant rose gold business card is a beautiful way to add luxury to your brand. This vintage cardstock has a beautiful shine that is reminiscent of a precious metal and is created by plating 0.5mm thick stainless steel. Die cut and non-bleed etching is included in the base price of the cards and is perfect when combined with our add-on, spot colour. Whether your looking for a new visiting business card or an elite membership card this is an excellent option.',
                'turnaround_time' => '14- 20 Business Days + Transit Time* 
*Turnaround is vary depending on job complexity, the job might be done earlier sometimes. Should you have any question, please feel free to contact us.',
                'guide_link' => '',
                'meta_tag' => 'metal business cards, metal name cards, visiting card design, cool business cards, creative business cards',
                'meta_description' => 'Rose gold metal business cards, only from Rockdesign.com. Available printing features : laser engraving, etching, cut through, UV printing and more ! ',
                'weight' => 0.040000000000000000832667268468867405317723751068115234375,
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'rose-gold-metal-business-cards',
                'pricing' => 1,
                'atleast_one' => 1,
                'status' => 1,
                'created_at' => '2016-03-11 08:42:19',
                'updated_at' => '2016-03-30 19:26:12',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}
