<?php

use Illuminate\Database\Seeder;

class CardFeaturesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('card_features')->delete();
        
        \DB::table('card_features')->insert(array (
            0 => 
            array (
                'id' => 1,
                'card_id' => 1,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'card_id' => 1,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'card_id' => 1,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'card_id' => 1,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'card_id' => 1,
                'name' => 'Emboss/Deboss',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            5 => 
            array (
                'id' => 7,
                'card_id' => 1,
                'name' => 'Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            6 => 
            array (
                'id' => 8,
                'card_id' => 1,
                'name' => 'Metallic Ink',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            7 => 
            array (
                'id' => 9,
                'card_id' => 1,
                'name' => 'Thermography',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            8 => 
            array (
                'id' => 11,
                'card_id' => 2,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            9 => 
            array (
                'id' => 12,
                'card_id' => 2,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            10 => 
            array (
                'id' => 13,
                'card_id' => 2,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            11 => 
            array (
                'id' => 14,
                'card_id' => 2,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 2,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            12 => 
            array (
                'id' => 15,
                'card_id' => 2,
                'name' => 'Emboss/Deboss',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 3,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            13 => 
            array (
                'id' => 16,
                'card_id' => 2,
                'name' => 'Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 4,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            14 => 
            array (
                'id' => 17,
                'card_id' => 2,
                'name' => 'Metallic Ink',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 5,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            15 => 
            array (
                'id' => 18,
                'card_id' => 2,
                'name' => 'Thermography',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 6,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            16 => 
            array (
                'id' => 20,
                'card_id' => 3,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            17 => 
            array (
                'id' => 21,
                'card_id' => 3,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            18 => 
            array (
                'id' => 22,
                'card_id' => 3,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            19 => 
            array (
                'id' => 23,
                'card_id' => 3,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            20 => 
            array (
                'id' => 24,
                'card_id' => 3,
                'name' => 'Emboss/Deboss',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            21 => 
            array (
                'id' => 25,
                'card_id' => 3,
                'name' => 'Metallic Ink',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            22 => 
            array (
                'id' => 26,
                'card_id' => 3,
                'name' => 'Thermography',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            23 => 
            array (
                'id' => 27,
                'card_id' => 4,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 1,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            24 => 
            array (
                'id' => 28,
                'card_id' => 4,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 2,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            25 => 
            array (
                'id' => 29,
                'card_id' => 4,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 3,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            26 => 
            array (
                'id' => 30,
                'card_id' => 4,
                'name' => 'Offset Print',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 4,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            27 => 
            array (
                'id' => 31,
                'card_id' => 4,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 5,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            28 => 
            array (
                'id' => 32,
                'card_id' => 4,
                'name' => 'Emboss/Deboss',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 6,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            29 => 
            array (
                'id' => 33,
                'card_id' => 4,
                'name' => 'Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 7,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            30 => 
            array (
                'id' => 36,
                'card_id' => 4,
                'name' => 'Thermography',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 9,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            31 => 
            array (
                'id' => 37,
                'card_id' => 5,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            32 => 
            array (
                'id' => 38,
                'card_id' => 5,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            33 => 
            array (
                'id' => 39,
                'card_id' => 5,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            34 => 
            array (
                'id' => 40,
                'card_id' => 5,
                'name' => 'Offset Print',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            35 => 
            array (
                'id' => 41,
                'card_id' => 5,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            36 => 
            array (
                'id' => 42,
                'card_id' => 5,
                'name' => 'Emboss',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            37 => 
            array (
                'id' => 44,
                'card_id' => 5,
                'name' => 'Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            38 => 
            array (
                'id' => 45,
                'card_id' => 5,
                'name' => 'Metallic Ink',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            39 => 
            array (
                'id' => 46,
                'card_id' => 5,
                'name' => 'Thermography',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            40 => 
            array (
                'id' => 48,
                'card_id' => 6,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            41 => 
            array (
                'id' => 49,
                'card_id' => 6,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            42 => 
            array (
                'id' => 50,
                'card_id' => 6,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            43 => 
            array (
                'id' => 51,
                'card_id' => 6,
                'name' => 'Offset Print',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            44 => 
            array (
                'id' => 52,
                'card_id' => 6,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            45 => 
            array (
                'id' => 53,
                'card_id' => 6,
                'name' => 'Emboss/Deboss',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            46 => 
            array (
                'id' => 54,
                'card_id' => 6,
                'name' => 'Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            47 => 
            array (
                'id' => 55,
                'card_id' => 6,
                'name' => 'Metallic Ink',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            48 => 
            array (
                'id' => 56,
                'card_id' => 6,
                'name' => 'Thermography',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            49 => 
            array (
                'id' => 58,
                'card_id' => 7,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            50 => 
            array (
                'id' => 59,
                'card_id' => 7,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            51 => 
            array (
                'id' => 60,
                'card_id' => 7,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            52 => 
            array (
                'id' => 61,
                'card_id' => 7,
                'name' => 'Offset Print',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            53 => 
            array (
                'id' => 62,
                'card_id' => 7,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            54 => 
            array (
                'id' => 63,
                'card_id' => 7,
                'name' => 'Emboss',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            55 => 
            array (
                'id' => 64,
                'card_id' => 7,
                'name' => 'Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            56 => 
            array (
                'id' => 65,
                'card_id' => 7,
                'name' => 'Metallic Ink',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            57 => 
            array (
                'id' => 66,
                'card_id' => 7,
                'name' => 'Thermography',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            58 => 
            array (
                'id' => 68,
                'card_id' => 8,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            59 => 
            array (
                'id' => 69,
                'card_id' => 8,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            60 => 
            array (
                'id' => 70,
                'card_id' => 8,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            61 => 
            array (
                'id' => 71,
                'card_id' => 8,
                'name' => 'Letterpress',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            62 => 
            array (
                'id' => 72,
                'card_id' => 8,
                'name' => 'Offset Print',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            63 => 
            array (
                'id' => 73,
                'card_id' => 8,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            64 => 
            array (
                'id' => 74,
                'card_id' => 8,
                'name' => 'Emboss/Deboss',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            65 => 
            array (
                'id' => 75,
                'card_id' => 8,
                'name' => 'Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            66 => 
            array (
                'id' => 76,
                'card_id' => 8,
                'name' => 'Metallic Ink',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            67 => 
            array (
                'id' => 77,
                'card_id' => 8,
                'name' => 'Thermography',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            68 => 
            array (
                'id' => 79,
                'card_id' => 4,
                'name' => 'Metallic Ink',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 8,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            69 => 
            array (
                'id' => 80,
                'card_id' => 9,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            70 => 
            array (
                'id' => 81,
                'card_id' => 9,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            71 => 
            array (
                'id' => 82,
                'card_id' => 9,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            72 => 
            array (
                'id' => 83,
                'card_id' => 9,
                'name' => 'Offset Print',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            73 => 
            array (
                'id' => 84,
                'card_id' => 9,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            74 => 
            array (
                'id' => 85,
                'card_id' => 9,
                'name' => 'Emboss/Deboss',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            75 => 
            array (
                'id' => 86,
                'card_id' => 9,
                'name' => 'Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            76 => 
            array (
                'id' => 87,
                'card_id' => 9,
                'name' => 'Metallic Ink',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            77 => 
            array (
                'id' => 88,
                'card_id' => 9,
                'name' => 'Thermography',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            78 => 
            array (
                'id' => 90,
                'card_id' => 10,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            79 => 
            array (
                'id' => 91,
                'card_id' => 10,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            80 => 
            array (
                'id' => 92,
                'card_id' => 10,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            81 => 
            array (
                'id' => 93,
                'card_id' => 10,
                'name' => 'Offset Print',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            82 => 
            array (
                'id' => 94,
                'card_id' => 10,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            83 => 
            array (
                'id' => 95,
                'card_id' => 10,
                'name' => 'Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            84 => 
            array (
                'id' => 96,
                'card_id' => 10,
                'name' => 'Metallic Ink',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            85 => 
            array (
                'id' => 98,
                'card_id' => 10,
                'name' => 'Spot UV',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            86 => 
            array (
                'id' => 99,
                'card_id' => 11,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 1,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            87 => 
            array (
                'id' => 100,
                'card_id' => 11,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 2,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            88 => 
            array (
                'id' => 101,
                'card_id' => 11,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 3,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            89 => 
            array (
                'id' => 102,
                'card_id' => 11,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 4,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            90 => 
            array (
                'id' => 103,
                'card_id' => 11,
                'name' => 'Emboss/Deboss',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 5,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            91 => 
            array (
                'id' => 104,
                'card_id' => 11,
                'name' => 'Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 6,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            92 => 
            array (
                'id' => 105,
                'card_id' => 11,
                'name' => 'Metallic Ink',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 7,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            93 => 
            array (
                'id' => 107,
                'card_id' => 11,
                'name' => 'Thermography',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 8,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            94 => 
            array (
                'id' => 108,
                'card_id' => 12,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            95 => 
            array (
                'id' => 109,
                'card_id' => 12,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            96 => 
            array (
                'id' => 110,
                'card_id' => 12,
                'name' => 'Metal Type',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            97 => 
            array (
                'id' => 111,
                'card_id' => 12,
                'name' => 'Custom Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            98 => 
            array (
                'id' => 112,
                'card_id' => 12,
                'name' => 'Etch',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            99 => 
            array (
                'id' => 113,
                'card_id' => 12,
                'name' => 'Spot Color',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            100 => 
            array (
                'id' => 114,
                'card_id' => 12,
                'name' => 'Laser Engrave',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            101 => 
            array (
                'id' => 115,
                'card_id' => 12,
                'name' => 'Variable Data',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            102 => 
            array (
                'id' => 116,
                'card_id' => 13,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            103 => 
            array (
                'id' => 117,
                'card_id' => 13,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            104 => 
            array (
                'id' => 118,
                'card_id' => 13,
                'name' => 'Metal Type',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 1,
                'is_required' => 1,
            ),
            105 => 
            array (
                'id' => 119,
                'card_id' => 13,
                'name' => 'Custom Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            106 => 
            array (
                'id' => 120,
                'card_id' => 13,
                'name' => 'Etch',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            107 => 
            array (
                'id' => 121,
                'card_id' => 13,
                'name' => 'Spot Color',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            108 => 
            array (
                'id' => 122,
                'card_id' => 13,
                'name' => 'Laser Engrave',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            109 => 
            array (
                'id' => 123,
                'card_id' => 13,
                'name' => 'Variable Data',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            110 => 
            array (
                'id' => 124,
                'card_id' => 14,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 1,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            111 => 
            array (
                'id' => 125,
                'card_id' => 14,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 2,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            112 => 
            array (
                'id' => 127,
                'card_id' => 14,
                'name' => 'Etch',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 2,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            113 => 
            array (
                'id' => 128,
                'card_id' => 14,
                'name' => 'Spot Color',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 3,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            114 => 
            array (
                'id' => 129,
                'card_id' => 14,
                'name' => 'Laser Engrave',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 4,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            115 => 
            array (
                'id' => 130,
                'card_id' => 14,
                'name' => 'Variable Data',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 5,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            116 => 
            array (
                'id' => 131,
                'card_id' => 15,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            117 => 
            array (
                'id' => 132,
                'card_id' => 15,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            118 => 
            array (
                'id' => 133,
                'card_id' => 15,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            119 => 
            array (
                'id' => 134,
                'card_id' => 15,
                'name' => 'UV Printing',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            120 => 
            array (
                'id' => 135,
                'card_id' => 16,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            121 => 
            array (
                'id' => 136,
                'card_id' => 16,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            122 => 
            array (
                'id' => 137,
                'card_id' => 16,
                'name' => 'UV Printing',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            123 => 
            array (
                'id' => 138,
                'card_id' => 16,
                'name' => 'White Ink',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            124 => 
            array (
                'id' => 139,
                'card_id' => 17,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            125 => 
            array (
                'id' => 140,
                'card_id' => 17,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            126 => 
            array (
                'id' => 141,
                'card_id' => 17,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            127 => 
            array (
                'id' => 142,
                'card_id' => 17,
                'name' => 'UV Printing',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            128 => 
            array (
                'id' => 143,
                'card_id' => 18,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            129 => 
            array (
                'id' => 144,
                'card_id' => 19,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            130 => 
            array (
                'id' => 145,
                'card_id' => 20,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            131 => 
            array (
                'id' => 146,
                'card_id' => 21,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            132 => 
            array (
                'id' => 147,
                'card_id' => 22,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            133 => 
            array (
                'id' => 148,
                'card_id' => 22,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            134 => 
            array (
                'id' => 149,
                'card_id' => 22,
                'name' => 'Metal Type',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            135 => 
            array (
                'id' => 150,
                'card_id' => 22,
                'name' => 'Template',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            136 => 
            array (
                'id' => 152,
                'card_id' => 22,
                'name' => 'Laser Engrave',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            137 => 
            array (
                'id' => 153,
                'card_id' => 21,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            138 => 
            array (
                'id' => 154,
                'card_id' => 21,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            139 => 
            array (
                'id' => 155,
                'card_id' => 21,
                'name' => 'Laser Engrave',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            140 => 
            array (
                'id' => 156,
                'card_id' => 21,
                'name' => 'Laser Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            141 => 
            array (
                'id' => 157,
                'card_id' => 20,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            142 => 
            array (
                'id' => 158,
                'card_id' => 20,
                'name' => 'Full Color Offset',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            143 => 
            array (
                'id' => 159,
                'card_id' => 20,
                'name' => 'Spot UV',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            144 => 
            array (
                'id' => 160,
                'card_id' => 20,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            145 => 
            array (
                'id' => 161,
                'card_id' => 19,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            146 => 
            array (
                'id' => 162,
                'card_id' => 19,
                'name' => 'Full Color Offset',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            147 => 
            array (
                'id' => 163,
                'card_id' => 19,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            148 => 
            array (
                'id' => 164,
                'card_id' => 19,
                'name' => 'Die Cut Corners',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            149 => 
            array (
                'id' => 165,
                'card_id' => 20,
                'name' => 'Die Cut Corners',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            150 => 
            array (
                'id' => 166,
                'card_id' => 18,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            151 => 
            array (
                'id' => 167,
                'card_id' => 18,
                'name' => 'Full Color Offset',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            152 => 
            array (
                'id' => 168,
                'card_id' => 18,
                'name' => 'Spot UV',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            153 => 
            array (
                'id' => 169,
                'card_id' => 18,
                'name' => 'Foil Stamp',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            154 => 
            array (
                'id' => 170,
                'card_id' => 18,
                'name' => 'Die Cut Corners',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            155 => 
            array (
                'id' => 171,
                'card_id' => 17,
                'name' => 'White Ink',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            156 => 
            array (
                'id' => 173,
                'card_id' => 23,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            157 => 
            array (
                'id' => 174,
                'card_id' => 23,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            158 => 
            array (
                'id' => 175,
                'card_id' => 23,
                'name' => 'Metal Type',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            159 => 
            array (
                'id' => 176,
                'card_id' => 23,
                'name' => 'Surface Finish',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            160 => 
            array (
                'id' => 177,
                'card_id' => 23,
                'name' => 'Custom Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            161 => 
            array (
                'id' => 178,
                'card_id' => 23,
                'name' => 'Etch',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            162 => 
            array (
                'id' => 179,
                'card_id' => 23,
                'name' => 'Spot Color',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            163 => 
            array (
                'id' => 180,
                'card_id' => 23,
                'name' => 'Laser Engrave',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            164 => 
            array (
                'id' => 181,
                'card_id' => 23,
                'name' => 'Variable Data',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            165 => 
            array (
                'id' => 182,
                'card_id' => 3,
                'name' => 'Edge Foil',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            166 => 
            array (
                'id' => 183,
                'card_id' => 3,
                'name' => 'Edge Paint',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            167 => 
            array (
                'id' => 184,
                'card_id' => 6,
                'name' => 'Edge Foil',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            168 => 
            array (
                'id' => 185,
                'card_id' => 6,
                'name' => 'Edge Paint',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            169 => 
            array (
                'id' => 186,
                'card_id' => 1,
                'name' => 'Edge Foil',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            170 => 
            array (
                'id' => 187,
                'card_id' => 1,
                'name' => 'Edge Paint',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            171 => 
            array (
                'id' => 188,
                'card_id' => 2,
                'name' => 'Edge Foil',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 7,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            172 => 
            array (
                'id' => 189,
                'card_id' => 2,
                'name' => 'Edge Paint',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 8,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            173 => 
            array (
                'id' => 190,
                'card_id' => 4,
                'name' => 'Edge Foil',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 10,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            174 => 
            array (
                'id' => 191,
                'card_id' => 4,
                'name' => 'Edge Paint',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 11,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            175 => 
            array (
                'id' => 192,
                'card_id' => 8,
                'name' => 'Edge Foil',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            176 => 
            array (
                'id' => 193,
                'card_id' => 8,
                'name' => 'Edge Paint',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            177 => 
            array (
                'id' => 194,
                'card_id' => 5,
                'name' => 'Edge Foil',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            178 => 
            array (
                'id' => 195,
                'card_id' => 5,
                'name' => 'Edge Paint',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            179 => 
            array (
                'id' => 196,
                'card_id' => 7,
                'name' => 'Edge Foil',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            180 => 
            array (
                'id' => 197,
                'card_id' => 7,
                'name' => 'Edge Paint',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            181 => 
            array (
                'id' => 198,
                'card_id' => 11,
                'name' => 'Edge Foil',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 9,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            182 => 
            array (
                'id' => 199,
                'card_id' => 11,
                'name' => 'Edge Paint',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 10,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            183 => 
            array (
                'id' => 200,
                'card_id' => 9,
                'name' => 'Edge Foil',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            184 => 
            array (
                'id' => 201,
                'card_id' => 9,
                'name' => 'Edge Paint',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            185 => 
            array (
                'id' => 202,
                'card_id' => 10,
                'name' => 'Edge Foil',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            186 => 
            array (
                'id' => 203,
                'card_id' => 10,
                'name' => 'Edge Paint',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            187 => 
            array (
                'id' => 204,
                'card_id' => 2,
                'name' => 'Offset Print',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 1,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            188 => 
            array (
                'id' => 210,
                'card_id' => 25,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 1,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            189 => 
            array (
                'id' => 211,
                'card_id' => 25,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 2,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            190 => 
            array (
                'id' => 212,
                'card_id' => 25,
                'name' => 'Card Stock',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 3,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            191 => 
            array (
                'id' => 213,
                'card_id' => 25,
                'name' => 'Laser Engrave',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 4,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            192 => 
            array (
                'id' => 215,
                'card_id' => 25,
                'name' => 'Laser Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 5,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            193 => 
            array (
                'id' => 239,
                'card_id' => 14,
                'name' => 'Metal Type',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 3,
                'is_print' => 0,
                'both_side' => 1,
                'is_required' => 1,
            ),
            194 => 
            array (
                'id' => 240,
                'card_id' => 30,
                'name' => 'Thickness',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            195 => 
            array (
                'id' => 241,
                'card_id' => 30,
                'name' => 'Size',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 0,
                'is_required' => 1,
            ),
            196 => 
            array (
                'id' => 242,
                'card_id' => 30,
                'name' => 'Metal Type',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 0,
                'is_print' => 0,
                'both_side' => 1,
                'is_required' => 1,
            ),
            197 => 
            array (
                'id' => 243,
                'card_id' => 30,
                'name' => 'Etch',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 2,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            198 => 
            array (
                'id' => 244,
                'card_id' => 30,
                'name' => 'Spot Color',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 3,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            199 => 
            array (
                'id' => 245,
                'card_id' => 30,
                'name' => 'Laser Engrave',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 4,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 1,
            ),
            200 => 
            array (
                'id' => 246,
                'card_id' => 30,
                'name' => 'Variable Data',
                'type' => 'checkbox',
                'link' => '',
                'sort' => 5,
                'is_print' => 1,
                'both_side' => 1,
                'is_required' => 0,
            ),
            201 => 
            array (
                'id' => 247,
                'card_id' => 14,
                'name' => 'Custom Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 1,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
            202 => 
            array (
                'id' => 248,
                'card_id' => 30,
                'name' => 'Custom Die Cut',
                'type' => 'dropdown',
                'link' => '',
                'sort' => 1,
                'is_print' => 1,
                'both_side' => 0,
                'is_required' => 1,
            ),
        ));
        
        
    }
}
