<?php

use Illuminate\Database\Seeder;

class TemplatesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('templates')->delete();
        
        \DB::table('templates')->insert(array (
            0 => 
            array (
                'id' => 2,
                'service_id' => 3,
                'card_id' => 1,
                'template_uid' => 'black-cards-0002',
                'name' => 'Minimalist Business Card Template -  Automatica',
                'description' => 'Clean and classic are both words that describe our Automatica template. On 25.6pt Black Duplex uncoated cardstock, this card remains relevant and timeless in its professional style. Showcasing the company’s name and logo in two sided black foil, and highlighting the contact details in one sided silver foil, this card is sure to leave a lasting impression. Automatica is a perfect option for any entrepreneur looking for a sleek, professional style.',
                'turnaround_time' => '12 - 16 business days + transit time*',
                'meta_tag' => '',
                'meta_description' => '',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'minimalist-business-card-template-automatica',
                'status' => 1,
                'purchased' => 1,
                'created_at' => '2016-02-11 22:44:29',
                'updated_at' => '2016-03-25 22:43:46',
            ),
            1 => 
            array (
                'id' => 3,
                'service_id' => 3,
                'card_id' => 9,
                'template_uid' => 'brown-kraft-cards-0001',
                'name' => 'Cool Business Card Template - Preface',
                'description' => 'Making use of our 22pt Kraft cardstock, our Preface template provides a clean professional look for any company. This minimalist design makes use of offset print on both sides of the card, as well as white foil to reverse type a message on the back.  The diagonal line on the face of this card invites the viewer to explore the back of the card. Almost reminiscent of a hang tag, this card draws the eye to the company name and is a perfect fit for artists and fashion businesses alike.',
                'turnaround_time' => '12 - 16 Business Days + Transit Time* ',
                'meta_tag' => 'kraft business cards',
                'meta_description' => '',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'cool-business-card-template-preface',
                'status' => 1,
                'purchased' => 3,
                'created_at' => '2016-02-11 22:58:40',
                'updated_at' => '2016-03-31 05:35:27',
            ),
            2 => 
            array (
                'id' => 4,
                'service_id' => 3,
                'card_id' => 19,
                'template_uid' => 'natural-cream-uncoated-cards-0001',
                'name' => 'Hello visiting Card Template',
                'description' => 'A wonderful way to greet and introduce yourself to clients is with our Hello card. On our Natural Cream uncoated cardstock, this lightweight card is ideal for the light hearted. Designed to be personable, this card uses two sided offset printing, and cursive font to create an endearing atmosphere. The back of the card is designed to look as though a bookmark is holding its place and uses a charming professional font. This card is excellent for writers, artists and creatives.',
                'turnaround_time' => '7 - 10 business days after proof approval + transit time',
                'meta_tag' => '',
                'meta_description' => '',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'hello-visiting-card-template',
                'status' => 1,
                'purchased' => 0,
                'created_at' => '2016-02-18 04:42:59',
                'updated_at' => '2016-02-18 04:42:59',
            ),
            3 => 
            array (
                'id' => 5,
                'service_id' => 3,
                'card_id' => 2,
                'template_uid' => 'duplex-cards-0001',
                'name' => 'Elegant Business Card Template',
                'description' => 'The Heraeus template embodies simple sophistication. The embossed circular letter uses matte gold and black foil to evoke a classic look that is reminiscent of a wax seal. With a thickness of 25.6pt, our uncoated Black/White Duplex cardstock has a firm but smooth feel, ideal for any professional who wishes to impress. The matte gold text adds a subtle but elegant touch to this superb design. The combination of the foil stamp along with the emboss feature leaves a lasting impression of luxury. ',
                'turnaround_time' => 'High End Business Cards: 12 - 16 business days + transit time*',
                'meta_tag' => '',
                'meta_description' => '',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'elegant-business-card-template',
                'status' => 1,
                'purchased' => 0,
                'created_at' => '2016-02-18 04:48:50',
                'updated_at' => '2016-02-22 21:29:25',
            ),
            4 => 
            array (
                'id' => 6,
                'service_id' => 3,
                'card_id' => 11,
                'template_uid' => 'gray-cards-0001',
                'name' => 'Typographic Visiting Card Template ',
                'description' => 'A business card is a reflection of your business, and often your client’s first impression of your company. If artistic and whimsical are words to describe your business then this is an excellent card for you. Designed with a light hearted font on the front, and a professional font on the back, this card is a great way to project both honesty and professionalism. The use of thermography on the front captures the beautiful colour of the dark gray 25.6pt duplex cardstock beneath, and creates a three dimensional shine. The white foil stamping on the reverse side is a bold contrast to the deep colour of the cardstock. This is an excellent card for artists, photographers, or anyone who is approaches their work with passion and creativity.',
                'turnaround_time' => 'High End Business Cards: 12 - 16 business days + transit time*',
                'meta_tag' => '',
                'meta_description' => '',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'typographic-visiting-card-template',
                'status' => 1,
                'purchased' => 0,
                'created_at' => '2016-02-18 04:53:58',
                'updated_at' => '2016-02-18 04:53:58',
            ),
            5 => 
            array (
                'id' => 7,
                'service_id' => 3,
                'card_id' => 6,
                'template_uid' => 'hard-suede-cards-0001',
                'name' => 'Luxury Retail Name Card Template',
                'description' => 'Crafted from our luxurious 30pt Hard Suede cardstock, our Tommy Martins template is simple yet refined. With a smooth leather-like feel, this card is certain to stand out among the competition. The combination of classic matte gold foil stamping with edging sends a clear message of sophistication and style - perfect for any professional. The clean lines in this design help to draw the viewer’s eye towards your logo as well as any important information you choose to include on the back of the card.
',
                'turnaround_time' => 'High End Business Cards: 12 - 16 business days + transit time*',
                'meta_tag' => '',
                'meta_description' => 'Crafted from our luxurious 30pt Hard Suede cardstock, our Tommy Martins template is simple yet refined. With a smooth leather-like feel, this card is certain to stand out among the competition. The combination of classic matte gold foil stamping with edging sends a clear message of sophistication and style - perfect for any professional. The clean lines in this design help to draw the viewer’s eye towards your logo as well as any important information you choose to include on the back of the card.',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'luxury-retail-name-card-template',
                'status' => 1,
                'purchased' => 0,
                'created_at' => '2016-02-18 05:05:59',
                'updated_at' => '2016-02-18 05:05:59',
            ),
            6 => 
            array (
                'id' => 8,
                'service_id' => 3,
                'card_id' => 1,
                'template_uid' => 'black-cards-0003',
                'name' => 'Corporate Black Business Card Template',
                'description' => 'Sentinel Surveillance is the perfect way to make a bold statement about your company. With silver and gold stamping on both the front and the back of our 25.6pt Black uncoated card stock, this card exemplifies true professionalism. The front design is reminiscent of a legal seal while the back of the card is designed to maintain an asymmetrical balance. The silver and gold foil highlights important information in a way that catches your client’s eye. This card is ideal for any business professional; lawyer, security officer, or stock broker.',
                'turnaround_time' => 'High End Business Cards: 12 - 16 business days + transit time*',
                'meta_tag' => '',
                'meta_description' => '',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'corporate-black-business-card-template',
                'status' => 1,
                'purchased' => 1,
                'created_at' => '2016-02-18 05:10:28',
                'updated_at' => '2016-03-30 05:16:33',
            ),
            7 => 
            array (
                'id' => 10,
                'service_id' => 3,
                'card_id' => 11,
                'template_uid' => 'gray-cards-0003',
                'name' => 'Tech Business Card Template',
                'description' => 'Less is more; this is especially true of our Metis card. Let these finishes speak for your company. This template is printed on our 26.5pt Dark Gray cardstock and is designed to highlight our silver and red foil stamping - which creates a symmetrical balance from front to back. The company name is used twice as a branding reinforcement. This is an excellent card choice for those in the high tech industry, or in the financial sector.',
                'turnaround_time' => 'High End Business Cards: 12 - 16 business days + transit time*',
                'meta_tag' => '',
                'meta_description' => '',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'tech-business-card-template',
                'status' => 1,
                'purchased' => 0,
                'created_at' => '2016-02-18 05:43:30',
                'updated_at' => '2016-02-18 05:43:30',
            ),
            8 => 
            array (
                'id' => 11,
                'service_id' => 3,
                'card_id' => 11,
                'template_uid' => 'gray-cards-0004',
                'name' => 'Emboss Business Card Template',
                'description' => 'On our 25.6pt Dark Gray cardstock our RockDesign template is an excellent minimalist card option. The blind emboss on the front of the card is a subtle yet effective way to showcase your branding. The three dimensional effect will literally make your company stand out. The reverse side the card uses metallic silver ink to create a subtle look. The off-centred spacing of the text, printed in metallic silver ink, balances the mirrored image of the emboss. The unexpected pop of colour on the edge of this card adds the perfect finishing touch. This colour can be changed to create an eye catching embellishment in your chosen hue. This template is excellent for publishing companies and law firms alike.',
                'turnaround_time' => 'High End Business Cards: 12 - 16 business days + transit time*',
                'meta_tag' => '',
                'meta_description' => 'On our 25.6pt Dark Gray cardstock our RockDesign template is an excellent minimalist card option. The blind emboss on the front of the card is a subtle yet effective way to showcase your branding. The three dimensional effect will literally make your company stand out. The reverse side the card uses metallic silver ink to create a subtle look. The off-centred spacing of the text, printed in metallic silver ink, balances the mirrored image of the emboss. The unexpected pop of colour on the edge of this card ',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'emboss-business-card-template',
                'status' => 1,
                'purchased' => 0,
                'created_at' => '2016-02-18 05:48:37',
                'updated_at' => '2016-02-18 05:48:37',
            ),
            9 => 
            array (
                'id' => 12,
                'service_id' => 3,
                'card_id' => 6,
                'template_uid' => 'hard-suede-cards-0002',
                'name' => 'Corporate Business Card Template',
                'description' => 'Elegant and simplistic in design, our Baron von Fancy card is a beautifully balanced template on 30pt Hard Suede. Using our metallic gold ink on both sides gives this card a brilliant shine. With a leather-like texture this card evokes the sensation of luxury and style - perfect for those in the auto sales industry. ',
                'turnaround_time' => 'High End Business Cards: 12 - 16 business days + transit time*',
                'meta_tag' => '',
                'meta_description' => '',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'corporate-business-card-template',
                'status' => 1,
                'purchased' => 0,
                'created_at' => '2016-02-18 05:53:16',
                'updated_at' => '2016-03-07 05:05:05',
            ),
            10 => 
            array (
                'id' => 13,
                'service_id' => 3,
                'card_id' => 9,
                'template_uid' => 'brown-kraft-cards-0002',
                'name' => 'Vintage Hang Tag Template',
                'description' => 'The Sylvan Collection hang tag is an obvious choice for entrepreneurs in the fashion and sales industry. Thanks to RockDesign’s simple die cut and hole punching services this card can be easily attached to merchandise. The contrast of black foil against the light Kraft cardstock, as well as the black foil in contrast to white foil on the back, gives this hang tag the impression of depth and sophistication. The 22pt Kraft cardstock also provides sense of sophistication and intimacy.',
                'turnaround_time' => '',
                'meta_tag' => '',
                'meta_description' => 'The Sylvan Collection hang tag is an obvious choice for entrepreneurs in the fashion and sales industry. Thanks to RockDesign’s simple die cut and hole punching services this card can be easily attached to merchandise. The contrast of black foil against the light Kraft cardstock, as well as the black foil in contrast to white foil on the back, gives this hang tag the impression of depth and sophistication. The 22pt Kraft cardstock also provides sense of sophistication and intimacy.',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'vintage-hang-tag-template',
                'status' => 1,
                'purchased' => 0,
                'created_at' => '2016-02-18 05:57:30',
                'updated_at' => '2016-02-18 05:57:30',
            ),
            11 => 
            array (
                'id' => 15,
                'service_id' => 3,
                'card_id' => 2,
                'template_uid' => 'duplex-cards-0002',
                'name' => 'Gold Typographic Name Card Template',
                'description' => 'Our Duplex Kraft card brings together the best of both worlds. The Little Things template combines our 22pt Kraft stock with our Smooth White to create a classic but edgy look. With two sided gold foil this card is a simplistic way to portray a message of poise and charm. The design on the front uses a font similar to hand writing to create a friendly and inviting look while the text on the back shows sophistication and professionalism. This card is perfect for salons, and businesses in the health industry.
',
                'turnaround_time' => '',
                'meta_tag' => '',
                'meta_description' => 'High End Business Cards: 12 - 16 business days + transit time*',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'gold-typographic-name-card-template',
                'status' => 1,
                'purchased' => 0,
                'created_at' => '2016-02-18 06:05:22',
                'updated_at' => '2016-02-18 06:05:22',
            ),
            12 => 
            array (
                'id' => 16,
                'service_id' => 3,
                'card_id' => 3,
                'template_uid' => 'triplex-cards-0001',
                'name' => 'Luxury Corporate Business Card Template ',
                'description' => '',
                'turnaround_time' => 'High End Business Cards: 12 - 16 business days + transit time*',
                'meta_tag' => '',
                'meta_description' => '',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'luxury-corporate-business-card-template',
                'status' => 1,
                'purchased' => 0,
                'created_at' => '2016-02-18 06:11:16',
                'updated_at' => '2016-02-18 06:11:16',
            ),
            13 => 
            array (
                'id' => 17,
                'service_id' => 3,
                'card_id' => 5,
                'template_uid' => 'premium-uncoated-cards-0001',
                'name' => 'Flourish Style Business Card Template',
                'description' => 'With delicately embossed floral patterns framing the offset printed text, this 17.4pt Premium White uncoated business card is an elegant way to represent your company. This card is designed to balance simplistic and classic text with an elaborate embossed pattern. Our Premium White cardstock is luxuriously embedded with goat hairs giving it a textured, rustic feeling. Popular with floral shops and bridal boutiques, this card is an excellent option for those looking to promote their business in an elegant way.
',
                'turnaround_time' => '12 - 16 business days after proof approval + transit time',
                'meta_tag' => '',
                'meta_description' => '',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'flourish-style-business-card-template',
                'status' => 1,
                'purchased' => 0,
                'created_at' => '2016-02-18 06:16:18',
                'updated_at' => '2016-02-18 06:16:18',
            ),
            14 => 
            array (
                'id' => 18,
                'service_id' => 3,
                'card_id' => 5,
                'template_uid' => 'premium-uncoated-cards-0002',
                'name' => 'Premium Name Card Template',
                'description' => 'Our Old Palace template is a stunning, vertically designed, business card. On our 17.4pt Premium White uncoated cardstock, this card has an interesting texture created by the embedded goat hairs. The rough texture of this card creates a luxurious and unique feel that is sure to set your company apart from the competition. Full bleed metallic ink is printed on the front of the card to create a grey metallic sheen. This metallic feature beautifully contrasts the simple offset print on the reverse of the card. The placement of the blind embossed logo is a subtle way to balance the silver foil stamp at the bottom of the card that highlights the company name. This card is an excellent option for those in the hospitality industry.
',
                'turnaround_time' => '12 - 16 business days after proof approval + transit time ',
                'meta_tag' => '',
                'meta_description' => '',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'premium-name-card-template',
                'status' => 1,
                'purchased' => 0,
                'created_at' => '2016-02-18 06:19:32',
                'updated_at' => '2016-02-18 22:58:05',
            ),
            15 => 
            array (
                'id' => 19,
                'service_id' => 3,
                'card_id' => 12,
                'template_uid' => 'black-metal-cards-0001',
                'name' => 'Photographer Business Card Template',
                'description' => 'Designed to look like an SLR camera, this 0.3 mm black metal business card is the perfect way for any photographer to leave a memorable impression. The cut through, black printing, etching, and laser engraving are all components that make this card the complete package. The design of this card includes a convenient outer loop that can be used for key chains. The cut through shutter provides not only detail to the camera as a whole, but adds aesthetic appeal to the reverse side of the card as well.',
                'turnaround_time' => '14 - 20 business days after proof approval + transit time',
                'meta_tag' => '',
                'meta_description' => '',
                'promotion_start_date' => NULL,
                'promotion_end_date' => NULL,
                'promotion_percent' => NULL,
                'slug' => 'photographer-business-card-template',
                'status' => 1,
                'purchased' => 0,
                'created_at' => '2016-02-18 06:23:44',
                'updated_at' => '2016-02-18 06:23:44',
            ),
        ));
        
        
    }
}
